server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "${CLIENT_ORIGIN:http://localhost:3000}"  # web app — unchanged
              - "http://localhost:8081"                    # Expo dev server
              - "http://192.168.1.7:8081"                 # your PC IP — replace x
              - "http://10.0.2.2:8081"   # ← add this for Android emulator (maps to localhost of the host machine)
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
              - "Authorization"        # ← needed for mobile Bearer token
              - "X-Refresh-Token"      # ← needed for mobile refresh token
            exposedHeaders:
              - "X-New-Access-Token"   # ← mobile needs to READ this from response
            allowCredentials: true

      routes:
        # ── AUTH — public, pas de token requis ──────────────────
        - id: auth-service-public
          uri: lb://SERVICE1-AUTH
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # ── USERS — protégé, passe par JwtAuthFilter ────────────
        - id: auth-service-users
          uri: lb://SERVICE1-AUTH
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

        # ── CONTENT ─────────────────────────────────────────────
        - id: content-service
          uri: lb://SERVICE3-CONTENT
          predicates:
            - Path=/content/**
          filters:
            - StripPrefix=1

        # ── POSTS ───────────────────────────────────────────────
        - id: posts-service
          uri: lb://SERVICE2-POSTS
          predicates:
            - Path=/posts/**
          filters:
            - StripPrefix=1

        # ── NOTIFICATIONS ────────────────────────────────────────
        - id: notifications-service
          uri: lb://SERVICE4-NOTIFICATION
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1

        # ── let the NOTIFICATIONS Socket public ────────────────────────────────────────
        - id: notifications-socket-http
          uri: lb://SERVICE4-NOTIFICATION
          predicates:
            - Path=/notifications-ws/**
          filters:
            - StripPrefix=1

        - id: notifications-socket-ws
          uri: lb:ws://SERVICE4-NOTIFICATION
          predicates:
            - Path=/notifications-ws/**
          filters:
            - StripPrefix=1

        # ── CONTENT-HUB ────────────────────────────────────────
        - id: content-hub-service
          uri: lb://SERVICE6-CONTENT-HUB
          predicates:
            - Path=/content-hub/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}   # Use the value of EUREKA_URL environment variable if it exists - If it doesn't exist → fall back to http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}

jwt:
  access-secret: K9f3Av1Pr6TwM2zQ8sL4uJ0bx7nYcR5e
  refresh-secret: W7yS2mE4qH8tN1dR5vY3kU9pZ6fB0cX2